
oc_user_login:
    path:     /login
    defaults: { _controller: OCUserBundle:Security:login }

oc_user_logout:
    path:     /logout
    
requete:
    path:     /requete
    defaults: { _controller: OCUserBundle:Reinitialisation:requete }

reinitialisation:
    path:     /reinitialisation/{token}
    defaults: { _controller: OCUserBundle:Reinitialisation:reinitialisation }

